### ISSUE TITLE
Exported MIDI file is broken

### ISSUE THREAD

**Issue by matevz** [canorusmusic/canorus#160]
I'm attaching a simple `c4 d e f | c d e f | g1` score:
[shortline.zip](https://github.com/canorusmusic/canorus/files/4447012/shortline.zip)

1. Open it with Canorus and export it to .mid.
2. Play it with timidity or other player.
3. Timidity crashes:
```
Requested buffer size 32768, fragment size 8192
ALSA pcm 'default' set buffer size 32768, period size 8192 bytes
Playing shortline.mid
MIDI file: shortline.mid
Format: 1  Tracks: 2  Divisions: 0
Text: Canorus Version 0.8.0rc1 generated. 
Text: It's still a work in progress.
Maxmum number of events is exceeded
Segmentation fault
```

Importing it with Canorus also doesn't work:
```
0x00005555557b1a6a in CAMidiImport::importMidiEvents (this=0x555557221010) at /home/matevz/apps/canorus/canorus-github/src/import/midiimport.cpp:190
190             pmidi_out.time = (pmidi_out.time * quarterLength) / pmidi_out.time_base;
(gdb) bt
#0  0x00005555557b1a6a in CAMidiImport::importMidiEvents() (this=0x555557221010) at /home/matevz/apps/canorus/canorus-github/src/import/midiimport.cpp:190
#1  0x00005555557b296b in CAMidiImport::importSheetImplPmidiParser(CASheet*) (this=0x555557221010, sheet=0x7fffb00049b0) at /home/matevz/apps/canorus/canorus-github/src/import/midiimport.cpp:348
#2  0x00005555557b1550 in CAMidiImport::importSheetImpl() (this=0x555557221010) at /home/matevz/apps/canorus/canorus-github/src/import/midiimport.cpp:115
#3  0x00005555557a9248 in CAImport::run() (this=0x555557221010) at /home/matevz/apps/canorus/canorus-github/src/import/import.cpp:122
#4  0x00007ffff505717d in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff6c236db in start_thread (arg=0x7fffb80bf700) at pthread_create.c:463
#6  0x00007ffff439c88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by matevz** [comment]
fixed
